- NumPy is a python library used for working with arrays and It was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.NumPy stands for Numerical Python.
- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.
- In NumPy dimensions are called <b>axes</b>.The number of dimensions is the <b>rank of the array</b> and the shape of an array is a tuple of integers giving the size of the array along each dimension.
- An array class(object) in Numpy is called as <b>ndarray</b>.It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality.
- Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

<b>Use Numpy</b>
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

<b>why fast</b>

- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.
- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [ ]:
#Installation
pip install numpy

In [1]:
#importing and rename name(alias)
import numpy as np

In [2]:
#Checking NumPy Version
print(np.__version__)

1.18.1


#### Array Creation

<b>array()</b>: Create a NumPy ndarray object by using the array() function.<br>

In [21]:
#Create a NumPy ndarray Object by using the array() function.
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [23]:
#if one is float then total will print as float
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [24]:
#the dimensions of the array --> matrix with n rows and m columns, shape will be (n,m).
print(b.shape)

(2, 3)


In [26]:
#an object describing the type of the elements in the array
print(a.dtype.name)
print(a.dtype)

#We can also give the type of elements should be
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

int32
int32
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [27]:
#the size in bytes of each element of the array.an array of elements of type float64 has itemsize 8 (=64/8) ->
# It is equivalent to ndarray.dtype.itemsize.
print(a.itemsize)

4


In [30]:
#the total number of elements of the array. This is equal to the product of the elements of shape.
print(a.size)

5


In [29]:
#type of the object passed -> arr is numpy.ndarray
print(type(b))

<class 'numpy.ndarray'>


In [28]:
#the buffer containing the actual elements of the array.
print(a.data)

#### Dimensions in Arrays

In [7]:
#0-D array
a = np.array(42)
print(a)
#uni-dimensional or 1-D array.
b = np.array([1, 2, 3, 4, 5])
print(b)

42
[1 2 3 4 5]


In [10]:
#2-D array--> used to represent matrix or 2nd order tensors.
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [8]:
#3-D array--> with two 2-D arrays
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
#ndarray.ndim--->the number of axes (dimensions) of the array.returns integer
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:
#Higher Dimensional Arrays
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)
print(arr.dtype.name)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
int32


#### Range, Reshaping

In [39]:
# we can also create with arange function -- arange(): numpy.arange([start, ]stop, [step, ], dtype=None)
a=np.arange(1,10)   
print(a)

#with step
b=np.arange(1,10,3)
print(b)

# it accepts float arguments
c=np.arange( 0, 2, 0.3 )                 
print(c)

[1 2 3 4 5 6 7 8 9]
[1 4 7]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [40]:
#reshape() function is used to give a new shape to an array without changing its data.

a = np.arange(6)                         # 1d array
print(a)

b = np.arange(12).reshape(4,3)           # 2d array
print(b)

c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### Accessing, Slicing

In [80]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

#Accessing the values in 1-D and 2-D
print(a[0], a[1], a[2])
print(b[0, 0], b[0, 1], b[1, 0])

#Negative Indexing
print(b[1, -1])

#addition with operator
print(a[2] + a[3])

1 2 3
1 2 6
10
7


In [48]:
# Change an element of the array of 1-D and 2-D
a[0] = 5                  
print(a)

b[0, 1] 
print(b)

[5 2 3]
[[1 2 3]
 [4 5 6]]


In [64]:
#Slicing arrays --->[start:end:step]
print(a[1:5])    #from index 1 to index 5 from the following array

print(a[4:])     #from index 4 to the end of the array

print(a[:4])     #from the beginning to index 4 (not included)

print(a[-3:-1])  #Slice from the index 3 from the end to index 1 from the end

print(a[ : :-1]) # reversed a

print(a[1:5:2]) #Return every other element from index 1 to index 5

print(a[::2])   #Return every other element from the entire array

print(b[1, 1:4])

print(b[0:2, 1:4])



[ 1  8 27 64]
[ 64 125 216 343 512 729]
[ 0  1  8 27]
[343 512]
[729 512 343 216 125  64  27   8   1   0]
[ 1 27]
[  0   8  64 216 512]
[7 8 9]
[[2 3 4]
 [7 8 9]]


In [62]:
#iterating
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [72]:
for i in a:
        print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [78]:
def f(x,y):
     return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
print(b)


#expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the 
#remaining axes. NumPy also allows you to write this using dots as b[i,...]

print(b[-1])                                  # the last row. Equivalent to b[-1,:]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[40 41 42 43]


In [77]:
#The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then
#x[1,2,...] is equivalent to x[1,2,:,:,:],
#x[...,3] to x[:,:,:,:,3] and
#x[4,...,5,:] to x[4,:,:,5,:].

c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
              [110,112,113]]])

print(c[1,...])                                   # same as c[1,:,:] or c[1]
print(c[...,2])                                   # same as c[:,:,2]

[40 41 42 43]
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


In [69]:
# if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator 
#over all the elements of the array
for element in b.flat:
        print(element)

1
2
3
4
5
6
7
8
9
10


In [68]:
#Iterating over multidimensional arrays is done with respect to the first axis
for row in a:
        print(row)

0
1
8
27
64
125
216
343
512
729
