In [2]:
#importing and rename name(alias)
import numpy as np

#### Functions

In [3]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)    

[[0. 0.]
 [0. 0.]]


In [4]:
b = np.ones((1,2))    # Create an array of all ones 
print(b)  

a=np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified
print(a)

[[1. 1.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [5]:
b=np.empty( (2,3) )                                 # uninitialized
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
c = np.full((2,2), 7)  # Create a constant array
print(c)     

[[7 7]
 [7 7]]


In [7]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)            

[[1. 0.]
 [0. 1.]]


In [8]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)       

[[0.39851453 0.18591117]
 [0.97027143 0.74262417]]


In [5]:
np.power(100, 8, dtype=np.int64)

10000000000000000

#### Basic Operations

In [12]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
print(c)

print(b**2)

print(10*np.sin(a))

print(a<35)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [13]:
A = np.array( [[1,1],
             [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print(A * B)                       # elementwise product
print(A @ B)                     # matrix product
print(A.dot(B))                # another matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [23]:
rg = np.random.default_rng(1)     # create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))

#such as += and *=, act in place to modify an existing array rather than create a new one
a *= 3
print(a)

b += a
print(b)


[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [30]:
import math as m
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,m.pi,3)
print(b.dtype.name)

c = a+b
print(c)
print(c.dtype.name)

d = np.exp(c*1j)
print(d)
print(d.dtype.name)


float64
[1.         2.57079633 4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [26]:
a = rg.random((2,3))

print(a.sum())

print(a.min())

print(a.max())

2.412007822394087
0.13404169724716475
0.7884287034284043


In [27]:
b = np.arange(12).reshape(3,4)

print(b.sum(axis=0) )                        # sum of each column

print(b.min(axis=1))                            # min of each row

print(b.cumsum(axis=1))                         # cumulative sum along each row

[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


#### Universal Functions<br>
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). 

In [31]:
B = np.arange(3)
print(B)

print(np.exp(B))
print(np.sqrt(B))

C = np.array([2., -1., 4.])
print(np.add(B, C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


#### Trigonometric functions

In [6]:
#sin
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. )

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [7]:
#cos
np.cos(np.array([0, np.pi/2, np.pi]))

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [12]:
#tan
from math import pi
np.tan(np.array([-pi,pi/2,pi]))

array([ 1.22464680e-16,  1.63312394e+16, -1.22464680e-16])

In [16]:
#Convert a degree array to radians
deg = np.arange(12.) * 30.
np.radians(deg)

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265, 3.66519143, 4.1887902 , 4.71238898,
       5.23598776, 5.75958653])

In [15]:
#Convert a radian array to degrees
rad = np.arange(12.)*np.pi/6
np.degrees(rad)

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
       330.])

##### Hyperbolic functions

In [17]:
np.sinh(np.pi*1j) # (exact value is 0)

(-0+1.2246467991473532e-16j)

In [18]:
np.cosh(0)

1.0

In [19]:
np.tanh((0, np.pi*1j, np.pi*1j/2))

array([0.+0.00000000e+00j, 0.-1.22464680e-16j, 0.+1.63312394e+16j])

In [21]:
np.arcsinh(np.array([np.e, 10.0]))   # with arc it is a inverse of that function

array([1.72538256, 2.99822295])

#### Rounding

In [28]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
#Return the truncated value of the input, element-wise.
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [29]:
#Return the ceiling of the input, element-wise.
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [30]:
#Return the floor of the input, element-wise.
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [27]:
#Round elements of the array to the nearest integer.
np.rint(a)

array([-2., -2., -0.,  0.,  2.,  2.,  2.])

#### Rational routines

In [31]:
#Returns the lowest common multiple of |x1| and |x2|
np.lcm(12, 20)

60

In [32]:
np.lcm.reduce([3, 12, 20])

60

In [33]:
np.lcm(np.arange(6), 20)

array([ 0, 20, 20, 60, 20, 20])

In [34]:
#Returns the greatest common divisor of |x1| and |x2|
np.gcd(12, 20)

4

##### Arithmetic operations

In [45]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.add(x1, x2)
np.subtract(1.0, 4.0)
np.divide(1.0, 4.0)
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [39]:
np.power(x1, x2)

array([[ 1.,  1.,  4.],
       [ 1.,  4., 25.],
       [ 1.,  7., 64.]])

In [46]:
np.remainder([4, 7], [2, 3])

array([0, 1], dtype=int32)

In [47]:
#Return element-wise quotient and remainder simultaneously.
np.divmod(np.arange(5), 3)

(array([0, 0, 0, 1, 1], dtype=int32), array([0, 1, 2, 0, 1], dtype=int32))

In [36]:
np.reciprocal([1, 2., 3.33])

array([1.       , 0.5      , 0.3003003])

In [40]:
np.negative([1.,-1.])

array([-1.,  1.])

In [38]:
np.positive([1.,-1.])

array([ 1., -1.])

#### Exponents and logarithms

In [48]:
np.log10([1e-15, -3.])

C:\Users\Vamshi Krishna\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([-15.,  nan])

In [49]:
x = np.array([0, 1, 2, 2**4])
np.log2(x)

C:\Users\Vamshi Krishna\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log2
  


array([-inf,   0.,   1.,   4.])

In [50]:
np.log([1, np.e, np.e**2, 0])

C:\Users\Vamshi Krishna\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([  0.,   1.,   2., -inf])

#### statistics

In [52]:
x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
np.cov(x,y) #Estimate a covariance matrix, given data and weights.

array([[11.71      , -4.286     ],
       [-4.286     ,  2.14413333]])

In [53]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [54]:
np.std(a)

1.118033988749895

In [55]:
np.var(a)

1.25

The ix_ function can be used to combine different vectors so as to obtain the result for each n-uplet. 

In [58]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])
ax,bx,cx = np.ix_(a,b,c)
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

#### Linear Algebra
numpy.linalg --module

In [61]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [63]:
# inverse of a matrix
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
y

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [64]:
#determinant of the input matrix.
np.linalg.det(a)

-2.0000000000000004

In [65]:
np.vdot(x,y)#vector product

2.499999999999999